name: Auto PR to Master

on:
  push:
    branches:
      - test

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest test.py # Replace with your test command or file

    - name: Create Pull Request
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
      run: |
        PR_DATA=$(jq -n --arg title "Automated PR: Update master branch" \
          --arg head "test" \
          --arg base "main" \
          --arg body "Automated PR to merge changes from test into the main branch." \
          '{title: $title, head: $head, base: $base, body: $body}')
        curl \
          -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d "$PR_DATA"
