name: Python Testing and Auto PR to Master

on:
  push:
    branches:
      - test

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest test.py

    - name: Create Pull Request
      if: success()
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "test" # Your source branch
        destination_branch: "main" # Branch to create PR to
        pr_title: "Automated PR: Update master branch" # Title of the PR
        pr_body: "Automated PR to merge dev-branch changes into the master branch." # Content of the PR message
        github_token: ${{ secrets.MY_PERSONAL_TOKEN }} # Provided by GitHub Actions
