name: Auto PR to Master

on:
  push:
    branches:
      - test

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest test.py # Replace with your test command or file

    - name: Create Pull Request
      if: success() # Ensures the PR is created only if tests pass
      uses: repo-sync/pull-request@v2
      with:
       source_branch: "dev-branch" # Your source branch
       destination_branch: "master" # Branch to create PR to
       pr_title: "Automated PR: Update master branch" # Title of the PR
       pr_body: "Automated PR to merge dev-branch changes into the master branch." # Content of the PR message
       github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use the PAT instead of GITHUB_TOKEN
